export const ingredientList = [
  "apple",
  "apricot",
  "arugula",
  "asparagus",
  "avocado",
  "bacon",
  "baguette",
  "baking powder",
  "baking soda",
  "banana",
  "basil",
  "beans",
  "beef",
  "beef broth",
  "beetroot",
  "black beans",
  "black pepper",
  "blueberries",
  "bread",
  "bread crumbs",
  "broccoli",
  "brown rice",
  "brown sugar",
  "butter",
  "cabbage",
  "cacao powder",
  "cajun seasoning",
  "cake flour",
  "canned corn",
  "canned tomatoes",
  "cantaloupe",
  "capers",
  "carrot",
  "cashews",
  "cauliflower",
  "celery",
  "cheddar cheese",
  "cheese",
  "cherry",
  "chicken",
  "chicken breast",
  "chicken broth",
  "chickpeas",
  "chili flakes",
  "chili powder",
  "chives",
  "chocolate chips",
  "cilantro",
  "cinnamon",
  "clam",
  "cloves",
  "coconut milk",
  "coconut oil",
  "coconut sugar",
  "cod",
  "coffee",
  "coriander",
  "corn",
  "corn flour",
  "corn starch",
  "cottage cheese",
  "couscous",
  "crackers",
  "cranberries",
  "cream",
  "cream cheese",
  "cucumber",
  "cumin",
  "curry powder",
  "dates",
  "dill",
  "duck",
  "egg",
  "egg noodles",
  "eggplant",
  "evaporated milk",
  "farro",
  "feta",
  "fig",
  "fish",
  "flaxseed",
  "flour",
  "garlic",
  "garlic powder",
  "ginger",
  "goat cheese",
  "grapes",
  "green beans",
  "green onion",
  "ground beef",
  "ground chicken",
  "ground cinnamon",
  "ground cloves",
  "ground turkey",
  "ham",
  "heavy cream",
  "honey",
  "horseradish",
  "hot sauce",
  "jalapeño",
  "jasmine rice",
  "kale",
  "ketchup",
  "kidney beans",
  "kiwi",
  "lamb",
  "lard",
  "leek",
  "lemon",
  "lemon juice",
  "lentils",
  "lettuce",
  "lime",
  "lime juice",
  "linguine",
  "mango",
  "maple syrup",
  "marjoram",
  "mayonnaise",
  "milk",
  "mint",
  "mozzarella",
  "mushroom",
  "mustard",
  "nectarine",
  "nutmeg",
  "oats",
  "olive oil",
  "olives",
  "onion",
  "orange",
  "oregano",
  "papaya",
  "paprika",
  "parsley",
  "pasta",
  "parmesan",
  "peach",
  "peanut butter",
  "peanuts",
  "pear",
  "peas",
  "pecans",
  "pepper",
  "pepperoni",
  "pita",
  "pineapple",
  "pinto beans",
  "pistachios",
  "plum",
  "pomegranate",
  "poppy seeds",
  "pork",
  "potato",
  "powdered sugar",
  "pretzels",
  "prosciutto",
  "prunes",
  "pumpkin",
  "pumpkin seeds",
  "quinoa",
  "radish",
  "raisins",
  "raspberries",
  "red cabbage",
  "red onion",
  "red pepper",
  "ricotta",
  "rice",
  "rice noodles",
  "rice vinegar",
  "rolled oats",
  "rosemary",
  "rye bread",
  "saffron",
  "sage",
  "salmon",
  "salt",
  "sardines",
  "sausage",
  "scallion",
  "sesame oil",
  "sesame seeds",
  "shallot",
  "shrimp",
  "snap peas",
  "sour cream",
  "soy sauce",
  "spaghetti",
  "spinach",
  "squash",
  "steak",
  "strawberries",
  "sugar",
  "sunflower seeds",
  "sweet potato",
  "swiss cheese",
  "tahini",
  "tarragon",
  "tea",
  "thyme",
  "tofu",
  "tomato",
  "tomato paste",
  "tomato sauce",
  "tortilla",
  "tuna",
  "turkey",
  "turmeric",
  "vanilla extract",
  "vegetable broth",
  "vinegar",
  "walnuts",
  "water",
  "watermelon",
  "wheat flour",
  "white bread",
  "white rice",
  "white sugar",
  "whole milk",
  "whole wheat flour",
  "wild rice",
  "wine",
  "worcestershire sauce",
  "yeast",
  "yellow onion",
  "yogurt",
  "zucchini",
  "agave syrup",
  "almond butter",
  "almond flour",
  "almonds",
  "anchovies",
  "artichoke",
  "balsamic vinegar",
  "barley",
  "bay leaves",
  "black olives",
  "blackberries",
  "blue cheese",
  "bok choy",
  "bran flakes",
  "brussels sprouts",
  "bulgur",
  "buttermilk",
  "canned beans",
  "canned peaches",
  "canned pineapple",
  "caraway seeds",
  "cardamom",
  "carnation milk",
  "celery root",
  "chia seeds",
  "chili sauce",
  "chocolate",
  "cider vinegar",
  "clam juice",
  "clementine",
  "coconut",
  "coconut cream",
  "coconut flakes",
  "cod fillet",
  "collard greens",
  "condensed milk",
  "cornmeal",
  "cranberry sauce",
  "cream of mushroom soup",
  "cream of chicken soup",
  "cumin seeds",
  "custard powder",
  "dark chocolate",
  "dark soy sauce",
  "demerara sugar",
  "duck breast",
  "edamame",
  "egg roll wrappers",
  "fennel",
  "fennel seeds",
  "fettuccine",
  "flour tortillas",
  "focaccia",
  "garam masala",
  "ginger powder",
  "graham crackers",
  "granola",
  "grapefruit",
  "ground cumin",
  "ground ginger",
  "ground pork",
  "guava",
  "haddock",
  "halibut",
  "hazelnuts",
  "herbes de provence",
  "hummus",
  "iceberg lettuce",
  "italian seasoning",
  "kidney",
  "kohlrabi",
  "lasagna noodles",
  "lemon zest",
  "lime zest",
  "lingonberries",
  "mackerel",
  "mandarin",
  "marinara sauce",
  "mascarpone",
  "miso paste",
  "molasses",
  "monterey jack",
  "muesli",
  "mustard seeds",
  "navy beans",
  "nutella",
  "oat milk",
  "okra",
  "paneer",
  "pancetta",
  "panko",
  "parsnip",
  "pearl barley",
  "pepper jack",
  "pickles",
  "pine nuts",
  "popcorn kernels",
  "porridge oats",
  "prosciutto ham",
  "red lentils",
  "romaine lettuce",
];
